### ISSUE TITLE
Consolidate dict and list variants.

### ISSUE THREAD

**Issue by danielballan** [oksanagit/deployAD#3]
Rather than having two copies, one as list and one as dict

https://github.com/oksanagit/deployAD/blob/91e7a289d95c27eec5ec7f2f125416c8a73e91a4/group_vars/all.yml#L47-L88

in order to support loops like

https://github.com/oksanagit/deployAD/blob/a8b4650af6d663b0ee29fa4de412cd537587ab51/roles/compile/tasks/main.yml#L13-L20

you can have a list _of_ dicts, like

```yaml
epics_modules:
  - name: asyn
    version: R4-37
```

and use it like

```yaml
 - name: build epics packages in the order specified in the list epics_modules.  
   command:  
   args: 
         cmd: make -sj 
         chdir: "{{deployment_dir}}/support/{{ item.name }}" 
   with_items: 
     - seq 
     - "{{ epics_modules }}" 
```

where the only change I've made is `{{ item }}` -> `{{ item.name }}`. If you variously need uppercase and lowercase versions (`ASYN` or `asyn`) in different situations, know that you can do `{{ item.name | upper }}` or `{{ item.name | lower}}`.

**Comment by danielballan** [comment]
```yaml
epics_modules:
  - name: asyn
    version: R4-37
  - name: iocStats
    release_name: DEVIOCSTATS
    version: 3.1.16
```

with usages like `{{ release_name | default(name) }}`, which uses the `release_name` if it's defined and falls back on the other `name` if not.
